### ISSUE TITLE
Add share in social networks in the annotation page

### ISSUE THREAD

**Issue by ferblape** [medialab-prado/consul#107]
In the sidebar, down the button, add the social network links.

If needed, ask help @martgnz to position the elements.

**Comment by furilo** [comment]
This can be closed, right?

**Comment by furilo** [comment]
The share box should be related to the comment, not the header section:

![captura de pantalla 2017-02-15 a las 17 32 25](https://cloud.githubusercontent.com/assets/24740/22984137/be7f39b2-f3a4-11e6-868e-6860c55eb247.png)

So we should make a column with the comment, and the sidebar with the share options.

**Comment by martgnz** [comment]
Addressed in https://github.com/medialab-prado/consul/pull/117
