### ISSUE TITLE
color levels not working

### ISSUE THREAD

**Issue by iacoco** [medialab-prado/consul#118]
There is a problem with color levels. When you create a new text highlight all the old highlighted text increase their intensity. Not matter if they are not in the same place!

**Comment by furilo** [comment]
Steps to reproduce: 

- Create an annotation of a full phrase
- Create an annotation of text inside that phrase

Result: 

- In the first step, 1 span is generated. OK
- In the second step, the span for the new annotation is created (correct), but another span is added to the full "parent" annotation

cc @ferblape

**Comment by ferblape** [comment]
For some reason, after creating the annotation, the plugin is calling to `search` again, and annotations are loaded twice. Maybe is related with the http storage:

https://github.com/medialab-prado/consul/blob/legislation-module-stable/app/assets/javascripts/legislation_annotatable.js.coffee#L167

**Comment by amaia** [comment]
@iacoco this one should be fixed in staging now, please check it out
