### ISSUE TITLE
selecting a highlighted text to view comments

### ISSUE THREAD

**Issue by iacoco** [medialab-prado/consul#119]
When we select a highlighted text to see comments we need to visualise which portion of the text these comments are related to. We have suggested to change the color of the selected text. (different from yellow).

**Comment by ferblape** [comment]
Hey @iacoco, we are higlighting the text of the selected annotation with an underlined. See the video:

![select text](https://cloud.githubusercontent.com/assets/17616/23220665/fc868444-f922-11e6-9a3c-e6b8f4ccebcf.gif)
