### ISSUE TITLE
Modify intensity if an annotation have various comments

### ISSUE THREAD

**Issue by furilo** [medialab-prado/consul#122]
Now we have a weird case: 

- an annotation might have 20 comments and many replies
- we have a section of text with 3 annotations, with only one comment each

The first annotation will be on the first level of coloring, while the second section, with way less comments is in level 3. We should modify the intensity also according to the number of comments of an annotation. 

Lets see if we can come up with a simple way of doing this for the moment. All these color map thing will have to be improved in other iterations. 

cc @ferblape @amaia

**Comment by amaia** [comment]
@furilo I think it would be confusing to use the same thing (color intensity) to mean two different things, annotation overlap and number of comments. As it is now you know that if you click on a darker part of the same sentence you'll see more specific (to that part) comment threads coming up, but if it also means that there are many comments in a single thread I think I would find it confusing. 
Let's talk about it on Monday.

**Comment by furilo** [comment]
@iacoco @rxnetwalker take a look in staging: https://consul.gobify.net/legislation/processes/3/draft_versions/4

**Comment by iacoco** [comment]
Parece que habéis conseguido que funcione el agrupamiento un poco mejor ?

Cuál es el cambio exactamente ?

2017-03-06 15:38 GMT+01:00 Álvaro Ortiz <notifications@github.com>:

**Comment by iacoco** [comment]
Vale ya veo. Tengo la duda de cómo funciona el agrupamiento. Claramente el
mapa de color creo que funciona mejor ahora.
Veo que valor tanto número de comentarios como votos sobre ellos y crea un
mapa que no se satura dado que el tope es el valor máximo del documento.
¿Es así ?

2017-03-06 22:38 GMT+01:00 Yago Bermejo Abati <iagobam@gmail.com>:

**Comment by furilo** [comment]
Si, exacto, estamos contando los puntos máximos de algún hilo, para tenerlo como referencia y que cualquier anotación sea en relación a eso.
