### ISSUE TITLE
Comment box elements if user not logged in

### ISSUE THREAD

**Issue by furilo** [medialab-prado/consul#125]
Two issues: 

- [ ] The "You need to log in box..." appears by default. I think it should only appear if you hover the "Publicar comentario" button. 

![captura de pantalla 2017-03-02 a las 15 47 37](https://cloud.githubusercontent.com/assets/24740/23512076/b035ad8e-ff5f-11e6-9baa-fb1326a81bf9.png)

- [ ] If you hover the voting controls, you get a box inviting to sign up of the full height of the container, which can get weird: 

![captura de pantalla 2017-03-02 a las 15 47 40](https://cloud.githubusercontent.com/assets/24740/23512125/d70df2ea-ff5f-11e6-8242-fdde6cd9db57.png)

**Comment by amaia** [comment]
@martgnz you probably need to remove this nbsp I added in a previous PR https://github.com/medialab-prado/consul/blob/legislation-module-stable/app/views/legislation/annotations/_comments_box.html.erb#L50

**Comment by martgnz** [comment]
Thanks @amaia, I'll look at this ASAP.
