### ISSUE TITLE
Management of recommended actions

### ISSUE THREAD

**Issue by jsperezg** [medialab-prado/consul#134]
The administration area must provide with a section that allows defining the recommended actions. Each recommended action will contain the following attributes:

* Name
* Description
* Picture
* Link
* Flag 'Request to administrators'
* Day offset: Number of days after the proposal publishment required to be available.
* Supports required: Number of supports required for the action to be available.
* Active (default true) Administrators will be allowed to temporarily disable actions.

The link or the flag 'Request for administrators' must have value. These attributes are exclusve. Receiving both informed will raise a validation error.

**Comment by SusanaNoguero** [comment]
The description should have a long text field to facilitate writing and reading

**Comment by SusanaNoguero** [comment]
I would add an extra field of "choose" date to activate an action. It will be useful for  specials actions  when  an special event  (for example "participatory budgets", a news on TV... ) is coming.

**Comment by SusanaNoguero** [comment]
![captura de pantalla 2018-06-29 a las 12 13 03](https://user-images.githubusercontent.com/37084132/42087462-8afbe416-7b96-11e8-8c6e-2617b817bb59.png)
