### ISSUE TITLE
Recommended actions

### ISSUE THREAD

**Issue by jsperezg** [medialab-prado/consul#135]
The Dashboard will offer a list of recommended actions. Only available actions will be shown. 

Each action will provide a checkbox to flag it as 'done'. 
The execution time will be recorded once its done and shown the list as well. 
Clicking the action will open the link provided by the administrator for the given action for all those actions that have the link informed. Actions with 'request to administrator' informed will create a request for the platform administrators.

**Comment by jsperezg** [comment]
Should the link be opened in a different tab?

**Comment by SusanaNoguero** [comment]
It would be more appropriate to manage the actions to be able to sort them from the list and not one by one. In any case the visualization of the list should follow the same order that would be seen in the proposal Dashboard.

**Comment by SusanaNoguero** [comment]
You need a button to remove added documents
