### ISSUE TITLE
Add support for proposals in draft state

### ISSUE THREAD

**Issue by jsperezg** [medialab-prado/consul#136]
Proposals created from the administration view will be published by default. However proposals created from the public side will be draft by default.

Draft proposals won't be available from the proposals list. They will be only available from the activity view of the proposal creator.

Once a proposal is created from the public side the user can:
* Publish the proposal.
* Preview the proposal.
* Navigate to the proposal dashboard.

Proposals in draft state can't receive supports.

![image](https://user-images.githubusercontent.com/1701962/41052507-356547c0-69b9-11e8-8b3a-bcf3df143f25.png)
![image](https://user-images.githubusercontent.com/1701962/41052515-3ad226b0-69b9-11e8-90f2-4df3c51107f2.png)
![image](https://user-images.githubusercontent.com/1701962/41052523-3f2ed410-69b9-11e8-955d-66c68374c8e2.png)
![image](https://user-images.githubusercontent.com/1701962/41052539-52903468-69b9-11e8-9451-71b83160c510.png)

**Comment by SusanaNoguero** [comment]
las propuestas en borrador son públicas pero sin módulo de apoyar, en su lugar podría haber el aviso de "propuesta cocinándose" no publicada o "en borrador".

**Comment by SusanaNoguero** [comment]
@jsperezg se prefiere no cargar más la página de listado de propuestas con más información. Yo pienso que finalmente tanto esa página como la de propuesta debería rediseñarse. Mi comentario  señalaba que la propuesta en estado borrador es pública (no sólo visible en Dashboard por el autor),el autor podrá difundirla  como las encuestas para generar interés y comunidad.

**Comment by jsperezg** [comment]
@SusanaNoguero eso está previsto. Puedes acceder a una propuesta en draft como usuario anónimo y no se filtra el acceso a la misma.

**Comment by jsperezg** [comment]
(comentario aranacm en slack)
Los mockups no serían exactamente como los que hay subidos. Este https://user-images.githubusercontent.com/1701962/41052515-3ad226b0-69b9-11e8-90f2-4df3c51107f2.png no sería así, sino que sería una banda de ese tipo, pero debajo se vería la propuesta en borrador. Es decir, sería el paso de "Previsualización".
