### ISSUE TITLE
Resource management

### ISSUE THREAD

**Issue by jsperezg** [medialab-prado/consul#142]
In addition to recommended actions (see #134) we must have resources as well. The administrator needs a management interface in order to define the available resources as well as when they will be available for users.

**Comment by jsperezg** [comment]
We should cosider add a type to actions defined in #134. Types could be either action or resource. This attribute will be used to decide later where they're accessed.

**Comment by jsperezg** [comment]
(Comentario aranacm en slack)

Como comentamos inicialmente la página de "acciones recomendadas" y de "recursos" va a ser la misma, que era un poco confusa la separación entre las dos. Tenedlo en cuenta a la hora de cómo mostrarlos. Quizás sería bueno tener un mockup de este aunque sea a grandes rasgos, para concretar los detalles.

**Comment by SusanaNoguero** [comment]
(comments from slack)
3 types of resources:
- The "manual" type with a description, an img and option to include one or several pdf and embed a video if needed
- The "request" type  (with a button) . It could have the same visual structure as the "manual".
- The "functionality or special page" type as would be the case of the survey resource.
