### ISSUE TITLE
Administrator requests

### ISSUE THREAD

**Issue by jsperezg** [medialab-prado/consul#150]
Create a view where administrators can check requests made by users. Each request will have the referral proposal and a check  to mark it as 'done'.

**Comment by SusanaNoguero** [comment]
<img width="1284" alt="captura de pantalla 2018-06-28 a las 11 55 25" src="https://user-images.githubusercontent.com/37084132/42027629-7944fbbc-7aca-11e8-9d88-fd800037cef5.png">

**Comment by SusanaNoguero** [comment]
<img width="1182" alt="captura de pantalla 2018-06-28 a las 11 55 41" src="https://user-images.githubusercontent.com/37084132/42027683-96656182-7aca-11e8-8be9-071c0220ef39.png">
