### ISSUE TITLE
 E-mail resource

### ISSUE THREAD

**Issue by SusanaNoguero** [medialab-prado/consul#229]
1. The message can be forwarded as many times as the user needs. It is not a limited resource.
2. There is a button on the resource description page, to preview and another to send. In the preview you can see the destination user's email.
3. There will be a short plain text at the beginning of the email and a subject that the user will be able to modify  in their his e-mail manager (not be able to enter text on the platform).

4. Details of the proposal included in the e-mail
-User's email (visible in preview)
-Proposal title: the size of the typeface must fit the length of the text. The tittle  links to the proposal in Decide.
Image: If there is an img in the proposal, it is added, if there is no one is included the default img ( (new mockup) 
The image links the proposal in Decide M.
-Button: "support that proposal" botton,links the proposal in Decide M 
-Links to share the proposal in networks: facebook, twiter and facebook

5. Data to register / evaluate the use of the resource:
-How many people click to see the proposal using this resource (at least) and become a user (if it is viable)
-How many proponents use the resource, that is, click on the "send" button in the email![Email_personalizado_foto_OK.jpg](https://images.zenhubusercontent.com/5b1933aa76f98d262074788a/3364e097-2183-42f0-96f8-dd51b28b0caa)![Email_personalizado_genérico_OK.jpg](https://images.zenhubusercontent.com/5b1933aa76f98d262074788a/1969d534-083a-44b9-adda-8dcbb0f26856)

**Comment by jsperezg** [comment]
5. is in context of audience measurement, this can be achieved using Google analytics or other similar tools

As we agreed in last sprint meeting:

The mail will include the proposal title, and proposal image, if any. In case it has no image defined the default image will be used.

Before the mail is set, notify the user about the recipient address.
