### ISSUE TITLE
Gráfico mi progreso error en el día del apoyo

### ISSUE THREAD

**Issue by SusanaNoguero** [medialab-prado/consul#250]
No corresponde el día del apoyo con el día en el que se visualiza.

**Comment by ailopezglez** [comment]
Hemos revisado y no hemos localizado en ningún sitio que ocurra este caso. Si tienes algún caso que mostrarnos te lo agradeceríamos.

**Comment by SusanaNoguero** [comment]
¿Habéis hecho la prueba de poner un apoyo en una gráfica? Y mirar en qué día
