### ISSUE TITLE
Bug editing legislation process dates

### ISSUE THREAD

**Issue by ferblape** [medialab-prado/consul#45]
When I update the "Fase de alegaciones" date, the "Proceso" date gets updated:

![screen shot 2016-12-30 at 10 51 00](https://cloud.githubusercontent.com/assets/17616/21563052/05ce8aa8-ce7e-11e6-8055-99af64f743e9.png)

**Extra ball:** could we udpate the format of the dates in the input text to be the same that uses Javascript. This way, when we update a date, we won't see the dates in two different formats.

**Comment by amaia** [comment]
@ferblape this should be fixed in #44

**Comment by ferblape** [comment]
Yep
