### ISSUE TITLE
Create links for legislation text sections

### ISSUE THREAD

**Issue by martgnz** [medialab-prado/consul#68]
In Sandbox we output a link in each section title with a reference to the same tag, so we can show an anchor when the user hovers over that title.

## Example
![screen shot 2017-01-17 at 10 32 37](https://cloud.githubusercontent.com/assets/1236790/22014992/742c8132-dca0-11e6-9281-46263cf54ac8.png)

**Comment by ferblape** [comment]
Low priority for the moment.
