### ISSUE TITLE
"Fechas clave" is partially out of viewport if browser window is not too narrow

### ISSUE THREAD

**Issue by furilo** [medialab-prado/consul#76]
![captura de pantalla 2017-01-18 a las 9 34 03](https://cloud.githubusercontent.com/assets/24740/22056634/48890e6c-dd61-11e6-9373-5e9fe24ffd33.png)

https://consul.gobify.net/legislation/processes/3

In the insides pages its different (ie. https://consul.gobify.net/legislation/processes/3/draft_versions/4 ) so just unifying it will fix it.

**Comment by martgnz** [comment]
Fixed in #82.
