### ISSUE TITLE
Header states: wrong state when 

### ISSUE THREAD

**Issue by furilo** [medialab-prado/consul#80]
When you are inside a text (ie. https://consul.gobify.net/legislation/processes/3/draft_versions/4 ) the middle section (the one that shows by default in the home) is not appearing when you open the header.
![captura de pantalla 2017-01-18 a las 9 41 42](https://cloud.githubusercontent.com/assets/24740/22056842/5637daf6-dd62-11e6-909d-f8e85abcd9f7.png)

**Comment by martgnz** [comment]
It should be fixed in #81.
