### ISSUE TITLE
Notification page breaks when notifiable is a Legislation::Question

### ISSUE THREAD

**Issue by amaia** [medialab-prado/consul#90]
Legislation Questions have an author to be compatible with the commenting system. When a user answers a question with comment that generated a notification for the author of the commented item (the question), but the notification page causes an exception when using `url_for` on a `Legislation::Question` object

```
NoMethodError: undefined method `legislation_question_url' for #<NotificationsController:0x007f2479420c08>
Did you mean? legislation_process_question_url
```
`/app/controllers/notifications_controller.rb:12`

**Comment by ferblape** [comment]
Fixed
