### ISSUE TITLE
Add more levels of annotation highlighting

### ISSUE THREAD

**Issue by ferblape** [medialab-prado/consul#97]
Right now there are only 3 levels of highlighting, add a few more, let's try with 8-10.

**Comment by furilo** [comment]
Finally how many elements of yellow do we have? For what can be seen in the live site it seems we keep having the same as before.

**Comment by ferblape** [comment]
We added 5 levels, but truth is that it's not enough. I'll take care.

**Comment by furilo** [comment]
Here is a test with 10 levels instead of 5. 

![captura de pantalla 2017-02-20 a las 11 46 48](https://cloud.githubusercontent.com/assets/24740/23121873/68708dc0-f762-11e6-9d4b-7d7850f449c2.png)

I don't think it works, because if you only have 1 level, it is not perceptible at all.

**Comment by martgnz** [comment]
As a sidenote, with this tool previewing color levels is quite easy: https://gka.github.io/palettes/#colors=#fffcee,#fee551|steps=10|bez=1|coL=1
